# Generated by Django 3.2.9 on 2021-12-09 15:10

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=80)),
                ('membership', models.IntegerField(choices=[(0, 'member'), (1, 'creator'), (2, 'admin')], default=0)),
                ('registered_on', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(blank=True, default='', max_length=50)),
                ('bio', models.TextField(blank=True, default='')),
                ('user_icon', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile',
                'ordering': ['registered_on'],
            },
        ),
    ]
