# Generated by Django 3.2.9 on 2021-12-01 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofiles',
            name='membership',
            field=models.IntegerField(choices=[(0, 'member'), (1, 'creator'), (2, 'admin')], default=0),
        ),
    ]
