# Generated by Django 3.2.9 on 2021-12-01 16:56

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_userprofile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_icon',
            field=cloudinary.models.CloudinaryField(default='v1638377416/placeholder.jpg', max_length=255, verbose_name='image'),
        ),
    ]
