# Generated by Django 3.2.9 on 2021-12-04 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_alter_userprofile_bio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['registered_on'], 'verbose_name': 'Profile'},
        ),
    ]
