# Generated by Django 3.2.9 on 2021-12-08 01:43

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_auto_20211206_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_icon',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
