# Generated by Django 3.2.9 on 2021-12-05 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promote_request', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='promoterequest',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
