# Generated by Django 3.2.9 on 2021-12-06 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promote_request', '0002_promoterequest_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promoterequest',
            name='reason',
            field=models.TextField(blank=True, default=''),
        ),
    ]
