# Generated by Django 3.2.9 on 2021-12-09 16:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('theme', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, default='', max_length=50)),
                ('report_type', models.IntegerField(choices=[(0, 'Others'), (1, 'Sensitive Speech'), (2, 'Personal Attack')], default=0)),
                ('description', models.TextField(blank=True, default='')),
                ('submit_on', models.DateTimeField(auto_now_add=True)),
                ('checked', models.BooleanField(default=False)),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theme_report', to='theme.theme')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_report', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submit_on'],
            },
        ),
    ]
