# Generated by Django 3.2.9 on 2021-12-25 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
