# Generated by Django 3.2.9 on 2021-12-06 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='excerpt',
            field=models.TextField(blank=True, default=''),
        ),
    ]
