# Generated by Django 3.2.9 on 2021-12-06 17:53

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0003_alter_comment_comment_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='feature_image',
            field=cloudinary.models.CloudinaryField(default='v1638492563/feature_img.jpg', max_length=255, verbose_name='image'),
        ),
    ]
