# Generated by Django 3.2.9 on 2021-12-08 01:43

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0004_alter_theme_feature_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='feature_image',
            field=cloudinary.models.CloudinaryField(default='featureimg', max_length=255, verbose_name='image'),
        ),
    ]
